from typing import Optional

from pydantic import Field

from app.models.base import BaseEntity
from app.models.enums import AlertSeverity, AlertStatus


class Alert(BaseEntity):
    """
    Represents a security alert generated by an EDR, SIEM,
    or another security product.
    """

    title: str
    description: str

    severity: AlertSeverity = AlertSeverity.LOW
    status: AlertStatus = AlertStatus.NEW

    asset_id: str

    investigation_id: Optional[str] = None

    confidence_score: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
    )