from app.models.analysis import Analysis
from app.models.report import Report


class ReportService:
    """
    Generates investigation reports from an Analysis.
    """

    def generate(
        self,
        analysis: Analysis,
        report_format: str = "MARKDOWN",
    ) -> Report:
        """
        Generate a report from an Analysis.
        """

        content = self._generate_content(
            analysis
        )

        return Report(
            analysis_id=analysis.id,
            content=content,
            report_format=report_format,
        )

    def _generate_content(
        self,
        analysis: Analysis,
    ) -> str:
        """
        Generate formatted report content.
        """

        findings = "\n".join(
            f"- {finding}"
            for finding in analysis.findings
        )

        recommendations = "\n".join(
            f"- {recommendation}"
            for recommendation in analysis.recommendations
        )

        mitre = "\n".join(
            analysis.mitre_techniques
        )

        iocs = "\n".join(
            analysis.iocs
        )

        return f"""
======================================================
                MYSTAI REPORT
======================================================

Investigation ID
----------------
{analysis.investigation_id}

Severity
--------
{analysis.severity.value}

Risk Score
----------
{analysis.risk_score:.1f} / 100

Confidence
----------
{analysis.confidence:.2f}

======================================================
EXECUTIVE SUMMARY
======================================================

{analysis.executive_summary}

======================================================
FINDINGS
======================================================

{findings}

======================================================
AI REASONING
======================================================

{analysis.reasoning}

======================================================
MITRE ATT&CK
======================================================

{mitre}

======================================================
INDICATORS OF COMPROMISE
======================================================

{iocs}

======================================================
RECOMMENDATIONS
======================================================

{recommendations}

======================================================
Generated by MystAI
======================================================
"""